name: Terraform

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  workflow_dispatch:
    inputs:
      actions:
        description: 'Terraform actions'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/TerraformOIDC
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        

      - name: Terraform Plan
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.actions == 'plan'
        run: terraform plan -target=module.s3 
        

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.actions == 'apply'
        run: terraform apply -target=module.s3 -auto-approve

      - name: Upload State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform.tfstate

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.actions == 'destroy'
        run: terraform destroy -auto-approve
        

